import Head from 'next/head'
import products from '../data/products.json'
import ProductCard from '../components/ProductCard'
import Layout from '../components/Layout'


export default function Home() {

	return (
		<>
			<Head>
				<title>µFE Demo | Products</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>

				<main>
					<h1>Products</h1>

					<br />
					<div className="product-list">
						{products.map((product, index) => (
							<ProductCard key={index} product={product} />
						))}
					</div>
				</main>
			</Layout>
		</>
	)
}
